/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eu.socialsensor.topicdetection;

/**
 *
 * @author gpetkos
 */
public class MainConstants {
    public static String TOPIC_DETECTION_METHOD="TOPIC_DETECTION_METHOD";
    public static String TWEETS_DIRECTORY="TWEETS_DIRECTORY";
    public static String TWEETS_FILE="TWEETS_FILE";
    public static String TEXT_BASED_DYSCO_CREATION_METHOD="TEXT_BASED_DYSCO_CREATION_METHOD";

    public static String TERM_SIMILARITY_METHOD="TERM_SIMILARITY_METHOD";
    
    
    public static String SHOW_TOPICS_ON_STD="SHOW_TOPICS_ON_STD";
    public static String N_TOPICS_TO_SAVE="N_TOPICS_TO_SAVE";
    public static String SAVE_TOPICS_ON_FILE="SAVE_TOPICS_ON_FILE";
    public static String RESULTS_FILE="RESULTS_FILE";
    public static String RESULTS_DIRECTORY="RESULTS_DIRECTORY";

//    public static BasicConfiguration TopicDetectionConfiguration;
    
    public static enum TOPIC_DETECTIONS_METHODS {BNGRAM,LDA,DOC_PIVOT,GRAPH_BASED,SOFT_FIM};
    public static enum TERM_SIMILARITY_METHODS {NO_OF_COOCCURRENCES,NO_OF_COOCCURRENCES_REGULARIZED_MIN,NO_OF_COOCCURRENCES_REGULARIZED_MAX,NO_OF_COOCCURRENCES_REGULARIZED_SUM,NO_OF_COOCCURRENCES_REGULARIZED_TIMES,JACCARD,COSINE};
    
    
    /*
    public static String TERM_SELECTION_METHOD="TERM_SELECTION_METHOD";
    public static String TERM_SELECTION_RATIO_THRESHOLD="TERM_SELECTION_RATIO_THRESHOLD";
    public static String TERM_SELECTION_TOP_N="TERM_SELECTION_TOP_N";
    public static String TERM_SELECTION_TOP_PERCENTAGE="TERM_SELECTION_TOP_PERCENTAGE";
    public static String MIN_TOPIC_SIZE="MIN_TOPIC_SIZE";
    public static String PERFORM_RERANKING="PERFORM_RERANKING";
    public static String DFIDFT_FILE="DFIDFT_FILE";

    public static String CORRELATION_SELECTION_TYPE="CORRELATION_SELECTION_TYPE";
    public static String CORRELATION_SELECTION_AVERAGE_DEGREE="CORRELATION_SELECTION_AVERAGE_DEGREE";
    public static String CORRELATION_THRESHOLD="CORRELATION_THRESHOLD";
    public static String CORRELATION_SELECTION_GLOBAL_N="CORRELATION_SELECTION_GLOBAL_N";
    public static String CORRELATION_SELECTION_GLOBAL_RATIO="CORRELATION_SELECTION_GLOBAL_RATIO";
    public static String CORRELATION_SELECTION_LOCAL_N="CORRELATION_SELECTION_LOCAL_N";
    public static String CORRELATION_SELECTION_LOCAL_RATIO="CORRELATION_SELECTION_LOCAL_RATIO";
    public static String TERM_SIMILARITY_METHOD="TERM_SIMILARITY_METHOD";
    public static String TOKENIZE_USERMENTIONS="TOKENIZE_USER_MENTIONS";
    public static String TOKENIZE_HASHTAGS="TOKENIZE_HASHTAGS";

    public static TERM_SIMILARITY_METHODS USED_TERM_SIMILARITY_METHOD=null;
        
    public static enum TERM_SELECTION_TYPES {RATIO_THRESHOLD,TOP_N,TOP_PERCENTAGE};
    public static enum CORRELATION_SELECTION_TYPES {GLOBAL_PERCENTAGE,GLOBAL_N,LOCAL_PERCENTAGE,LOCAL_N,FULL,THRESHOLD,GLOBAL_AVERAGE_DEGREE};
    public static enum TERM_SIMILARITY_METHODS {NO_OF_COOCCURRENCES,NO_OF_COOCCURRENCES_REGULARIZED_MIN,NO_OF_COOCCURRENCES_REGULARIZED_MAX,NO_OF_COOCCURRENCES_REGULARIZED_SUM,NO_OF_COOCCURRENCES_REGULARIZED_TIMES,JACCARD,COSINE};

    */

}
